on:
  pull_request:
    branches:
      - main

jobs:
  wilco:
    runs-on: ubuntu-latest  # Changed from 20.04
    env:
      DOCKER_API_VERSION: "1.44"
      CI: true
    name: Pr checks

    steps:
      - name: Check out project
        uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # ADD THIS STEP HERE
      - name: Lower Docker Min API Version
        run: |
          echo '{"min-api-version": "1.40"}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: "4.4"

      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Wilco checks
        id: Wilco
        uses: trywilco/actions@main
        with:
          engine: ${{ secrets.WILCO_ENGINE_URL }}
